/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './components/**/*.{js,vue,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts}',
    './nuxt.config.{js,ts}',
    './app.vue',
  ],
  theme: {
    screens: {
      sm: '480px',
      md: '768px',
      lg: '976px',
      xl: '1440px',
    },

    extend: {
      colors: {
        bgc: '#f0f2f5',
        'gray-dark': '#273444',
        gray: '#8492a6',
        'gray-light': '#d3dce6',
        primary: {
          color: '#014f77',
          bg: '#c0e0f1',
          'border-color': '#c0e0f1',
          'hover-color': '#013550',
          'hover-bg': '#81c2e3',
          'hover-border-color': '#81c2e3',
          'disabled-color': '#000',
          'disabled-bg': '#c0e0f1',
          'disabled-border-color': '#c0e0f1',
        },
        secondary: {
          color: '#171717',
          bg: '#f0f2f5',
          'border-color': '#f0f2f5',
          'hover-color': '#141414',
          'hover-bg': '#d8dadd',
          'hover-border-color': '#d8dadd',
          'disabled-color': '#000',
          'disabled-bg': '#f0f2f5',
          'disabled-border-color': '#f0f2f5',
        },
        success: {
          color: '#3d6208',
          bg: '#d9e8c3',
          'border-color': '#d9e8c3',
          'hover-color': '#284105',
          'hover-bg': '#b2d186',
          'hover-border-color': '#b2d186',
          'disabled-color': '#000',
          'disabled-bg': '#d9e8c3',
          'disabled-border-color': '#d9e8c3',
        },
        info: {
          color: '#05576b',
          bg: '#c1e4ec',
          'border-color': '#c1e4ec',
          'hover-color': '#033a47',
          'hover-bg': '#84c8d9',
          'hover-border-color': '#84c8d9',
          'disabled-color': '#000',
          'disabled-bg': '#c1e4ec',
          'disabled-border-color': '#c1e4ec',
        },
        warning: {
          color: '#824704',
          bg: '#f6ddc1',
          'border-color': '#f6ddc1',
          'hover-color': '#573002',
          'hover-bg': '#ecbb83',
          'hover-border-color': '#ecbb83',
          'disabled-color': '#000',
          'disabled-bg': '#f6ddc1',
          'disabled-border-color': '#f6ddc1',
        },
        danger: {
          color: '#841717',
          bg: '#f6c9c9',
          'border-color': '#f6c9c9',
          'hover-color': '#580f0f',
          'hover-bg': '#ee9393',
          'hover-border-color': '#ee9393',
          'disabled-color': '#000',
          'disabled-bg': '#f6c9c9',
          'disabled-border-color': '#f6c9c9',
        },
      },
    },
  },
  plugins: [],
}
